name: OCI Auto Instance Creator

on:
  schedule:
    # 10분마다 자동으로 인스턴스 생성을 시도합니다.
    - cron: '*/10 * * * *'
  workflow_dispatch: # 수동 실행 버튼 활성화

jobs:
  run-oci-creator:
    runs-on: ubuntu-latest
    steps:
      - name: Run OCI Instance Creator
        uses: mowirth/oci-instance-creator@master
        env:
          OCI_USER_ID: ${{ secrets.OCI_USER_ID }}
          OCI_TENANCY_ID: ${{ secrets.OCI_TENANCY_ID }}
          OCI_REGION: ${{ secrets.OCI_REGION }}
          OCI_FINGERPRINT: ${{ secrets.OCI_FINGERPRINT }}
          OCI_KEY_CONTENT: |
            ${{ secrets.OCI_KEY_CONTENT }}
          OCI_SUBNET_ID: ${{ secrets.OCI_SUBNET_ID }}
          OCI_IMAGE_ID: ${{ secrets.OCI_IMAGE_ID }}
          OCI_AVAILABILITY_DOMAIN: ${{ secrets.OCI_AVAILABILITY_DOMAIN }}
          SSH_KEY: ${{ secrets.SSH_KEY }}
          CPUS: 4
          RAM: 24
          SHAPE: VM.Standard.A1.Flex
